project:
  type: website

website:
  title: "Bhawna Shekhawat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
      - href: skills.qmd
        text: Skills
      - href: certifications.qmd
        text: Certifications
      - href: availability.qmd
        text: Availability

format:
  html:
    theme: cosmo
    toc: true
