project:
  type: website
  output-dir: docs

website:
  title: "bhawna-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - projects.qmd
      - contact.qmd









