project:
  type: website

website:
  title: "Bhawna Shekhawat"
  navbar: false
  page-footer: "© 2025 Bhawna Shekhawat. All rights reserved."

format:
  html:
    theme: cosmo
    css: styles.css







